### ISSUE TITLE
module 'collections' has no attribute 'Iterable'

### ISSUE THREAD

**Issue by iipr** [uvemas/ViTables#110]
After pip-installing vitables 3.0.2, trying to open it throws the error: `module 'collections' has no attribute 'Iterable'`
I think it is related to this stackoverflow question: [link](https://stackoverflow.com/questions/53978542/how-to-use-collections-abc-from-both-python-3-8-and-python-2-7/).
As a quick and dirty fix, manually replacing `collections` by `collections.abc` on the vitables file `utils.py` seems to work.

**Comment by ankostis** [comment]
Has been addressed by #109, awaiting for a new release.

**Comment by iipr** [comment]
Thanks @ankostis! I only just saw it.
