### ISSUE TITLE
Update README.txt

### ISSUE THREAD

**Issue by m3lab-zzl** [uvemas/ViTables#121]
Vitables deserves a more attractive README, we may:

- Change `.txt` to `.rst` or `.md` format, to have a better appearance.
- Add [badges](https://anaconda.org/conda-forge/vitables/badges) to show the version, download statistics, and much more.
- Add screenshots to show how vitables looks like.

I will be glad to create a PR for this.

What do you guys think?

**Comment by uvemas** [comment]
It seems a nice improvement so please go for it. TIA!
