### ISSUE TITLE
Funky behavior of CSV export plugin.

### ISSUE THREAD

**Issue by alexey-naydenov** [uvemas/ViTables#18]
Select a group,  open Dataset menu then the menu entry "Export  to CSV ..." will be greyed out. If you afterwards right click on any leaf node "Export  to CSV ..." will be grayed out as well in the context menu. If you open Dataset menu while a leaf is selected export to csv becomes enabled as well as context menu entry.

Problem: the same action is used in the main menu and the context menu so when the main menu actions is disabled the context menu entry is disabled as well. The main menu entry is disabled when Dataset menu is opened while a group is selected.

**Comment by cippo1987** [comment]
It works for me, but it is impossible to extract a subsection of a dimension>2 dataset.
