### ISSUE TITLE
Program terminates if plugin descriptions was changed.

### ISSUE THREAD

**Issue by alexey-naydenov** [uvemas/ViTables#25]
Hi,

There is a bug in plugin loading function. If one enables a plugin,  changes its description and copies the new version into plugin folder then vitables crashes without any output. The problem is in except handler in `pluginsloader.py` at line 214. KeyError is thrown before `mod_name` is defined so new exception is raised in exception handler.
Better change the handler to:

``` python
        except KeyError:
            LOGGER.error('\nError:  plugin {0} can not be found'.
                         format(UID))
            return
```

It is probably better not use plugin description for UID

Alexey

**Comment by uvemas** [comment]
Currently the plugin description is not used for UID.
