### ISSUE TITLE
Syntax Errors for Python 3.+

### ISSUE THREAD

**Issue by sobersoup** [uvemas/ViTables#29]
Several syntax errors were found in the following files:
vitables\h5db\dbdoc.py
vitables\queries\querydlg.py
vitables\preferences\vtconfig.py

All errors were part of the module's error handlers.

**Comment by kprussing** [comment]
After running `2to3` on the project, I also did not get any syntax errors. 

Furthering the discussion on Python 3 compatibility, do you need to continue supporting Python 2.6?  Apparently PyTables is [no longer](http://pytables.github.io/MIGRATING_TO_3.x.html) actively supporting versions of Python lower than 2.7.  On a whim, I launched the ViTables script using Python 2.7 and the only syntax related error that popped up immediately was importing `ConfigParser` which is all lower case in Python 3. `grep`ing the source tree, this appears to be the only module that uses camel case and is used in the four following files:

+ vitables/plugins/dbstreesort/aboutpage.py:
+ vitables/plugins/dbstreesort/dbs_tree_sort.py
+ vitables/plugins/timeseries/aboutpage.py
+ vitables/plugins/timeseries/time_series.py

A potential work around is to conditionally import `ConfigParser` based on the Python version.  

Now for my real question: Would you be open to accepting a pull request to convert to Python 3 syntax at the expense of dropping support for Python 2.6?

**Comment by uvemas** [comment]
Hi,

which branch are you talking about? I can't find imports of ConfigParser neither in the Python3-support nor in the develop branches. Please note that development in the master (and Python3-support) branch is frozen (apart from fixing bugs).

Support for Python2.6 is already dropped. It makes no sense to support it if PyTables doesn't. In addition as the project has only 2 developers and both of them are really busy the pace of development is very slow so supporting useless Python versions is not a choice.

Vicent

**Comment by kprussing** [comment]
That would explain it then. I started working on the master branch because it had the most recent activity, and I thought it was the primary branch. If the development branch is where the real work should be happening, I'll back up and start from there. Thanks for the note. Should this issue be closed now that this is no longer an issue?

**Comment by uvemas** [comment]
Hi,

I'm sorry if the current branches layout was confusing for you. I'm closing the issue.

Thanks for your comments.
