### ISSUE TITLE
PyQt5 support ?

### ISSUE THREAD

**Issue by stonebig** [uvemas/ViTables#40]
Does ViTables intend to support Qt5  ?

**Comment by uvemas** [comment]
Yes, but not in the near future. The problem is simple: the two main contributors (Alexey and I) are two busy and have no spare time for developing ViTables so the development pace is slow. Having more contributors would be a great help.

**Comment by avalentino** [comment]
Hi @uvemas I ported an application of mines ([gsdview](https://github.com/avalentino/gsdview)) to pyqt5 and it didn't took too much time.
FYI i developed a small adaption layer to allow my app to work also with pywt4 and pyside.
You can find it at https://github.com/avalentino/qtsix and on PyPI.

**Comment by uvemas** [comment]
Hi @avalentino, thanks a lot for your useful information. I'll try to have a look to your repo this weekend. Unfortunately I still don't know when I'll be able to continue the ViTables development.
