### ISSUE TITLE
Add option to make the row numbers start at 0

### ISSUE THREAD

**Issue by 153957** [uvemas/ViTables#42]
Since indexes in Python also start at 0 it would be easier if the row numbering in ViTables also allows for row numbering that start at 0.

**Comment by ankostis** [comment]
I agree on that - that would also make sense when viewing pandas dataframes.

**Comment by 153957** [comment]
@ankostis perhaps you could make a pull request for your commit?

**Comment by ankostis** [comment]
done it.

**Comment by stonebig** [comment]
any release plan for tonight ?

**Comment by uvemas** [comment]
Unfortunately not. Today I've fixed some obvious things but as I said in other thread (sorry I don't remember which one) I want to test the current version more in depth and fix important bugs, if any. I'll release after testing.
