### ISSUE TITLE
Strange unicode error when opening table

### ISSUE THREAD

**Issue by icarmi** [uvemas/ViTables#45]
Hello,

I'm new to ViTables so I may be doing something obviously wrong... :) But, I'm trying to open a table, and sometimes I get a strange unicode error. The reasons I find this strange are:
1. I'm not doing anything with special characters... Mostly numbers or strings that contain vanilla readable ascii characters...
2. Sometimes I get the error, and sometimes not, on the same table, depending (seemingly) on luck. 

Thanks!! This is the dump that I get:

ViTables 2.1
Copyright (c) 2008-2011 Vicent Mas.
All rights reserved.
Traceback (most recent call last):

  File "/usr/share/vitables/vitables/h5db/dbsTreeView.py", line 279, in mouseDoubleClickEvent

self.activateNode(current)

  File "/usr/share/vitables/vitables/h5db/dbsTreeView.py", line 146, in activateNode

self.vtapp.nodeOpen(index)

  File "/usr/share/vitables/vitables/vtapp.py", line 763, in nodeOpen

subwindow = dataSheet.DataSheet(index)

  File "/usr/share/vitables/vitables/vtTables/dataSheet.py", line 69, in **init**

title = unicode(leaf.title, 'utf_8')

  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode

return codecs.utf_8_decode(input, errors, True)

UnicodeDecodeError
: 
'utf8' codec can't decode byte 0x80 in position 0: invalid start byte

**Comment by nikoskaragiannakis** [comment]
I get a similar error message:

```
ViTables 2.1
Copyright (c) 2008-2011 Vicent Mas.
All rights reserved.
/usr/lib/python2.7/dist-packages/tables/group.py:1156: UserWarning: problems loading leaf ``/quote``::

  'utf8' codec can't decode byte 0x88 in position 0: invalid start byte

The leaf will become an ``UnImplemented`` node.
  % (self._g_join(childname), exc))
```

I opened the h5 file in ipython, where I didn't have any problem in reading the data inside every table.

**Comment by bobatsar** [comment]
I seem to have the same error running vitables on linux mint. Anyone any suggestions how to fix this? The same file can be opened in vitables on win7.

**Comment by uvemas** [comment]
unicode() is not used in the 3.0.0 release so I assume the bug is not present now and consider the bug closed. If you keep having unicode problems please file a new bug.
