### ISSUE TITLE
conda-env

### ISSUE THREAD

**Issue by jpfairbanks** [uvemas/ViTables#47]
Hi I just started using your ViTables and figured that some people who use it would benefit from a conda-env that had all the dependencies. If they run  `conda env environment.yml` where environment.yml is the following text, it will install all of the dependencies into a conda virtual environment. It took me a few minutes to put it together, and I figured that I would save someone else those few minutes.

```
name: vitables
dependencies:
  - numpy
  - h5py
  - sip
  - pyqt
  - pytables
```

At least it is an machine readable specification of the dependencies.

**Comment by gdementen** [comment]
As far as I know, the only direct dependencies are pyqt and pytables, numpy should be pulled by pytables, sip by pyqt, and h5py is not required.

**Comment by uvemas** [comment]
A conda environment is provided in the 3.0.0 release.
