### ISSUE TITLE
where can i found a windows installer for Vitables

### ISSUE THREAD

**Issue by ym80** [uvemas/ViTables#48]
please would mind helping me,

where can i found a windows installer for Vitables?
i have already installed pytables

my python version is 3.4

**Comment by ym80** [comment]
Would you please tell where can i found a vitable installer (.exe) 
plateform : windows
python : 3.4
Thanks in advance
regards

**Comment by uvemas** [comment]
Hi ym80,

links to available installers can be found in the [ViTables SourceForge page](https://sourceforge.net/projects/vitables/files/?source=navbar/).

Unfortunately there is no Windows installer for Python3.4. Currently the ViTables project is nearly unmaintained so I don't forsee the release of new installers anytime soon. If you want to help and contribute to the project (fixing bugs, writing code, creating installers...) you're welcome.

Sorry for not being more helpful.

**Comment by ym80** [comment]
Thank you

**Comment by ankostis** [comment]
Actually on Windows I've managed to run it using [WinPython](http://winpython.github.io/)[1] ans it runs just fine.  Use my very latest dev-derived branch:

    pip install git+https://github.com/ankostis/ViTables@qt5

[1] I've be using WinPython for the last 3 years and have solved all those pesky native dependencies problems on *Windows*.
WinPython it is a *regular* (no conda) python distributions with all scientific packages requiring native backends pre-built - it is materialized by the tireless @stonebig in collaboration with [Gohlke's Unofficial Win Binaries repo](http://www.lfd.uci.edu/~gohlke/pythonlibs/).
