### ISSUE TITLE
Query raise unhandled type error exception 

### ISSUE THREAD

**Issue by drc-bsorenson** [uvemas/ViTables#51]
On windows, when running a query, the user may get

    TypeError: slice indices must be integers or None or have an __index__ method

when running a query from ViTables.

The problem comes from this line in both `Query.queryWithNoIndex()`, and `Query.queryWithIndex()` (115 and 178, respectively).

    div = numpy.divide(stop - start, chunk_size)

This may return  a `float` instead of an `int` because of true_division in Python 3. Replacing it with 

     div = int((stop - start) // chunk_size)

I'd be happy to submit a pull request to fix this.

**Comment by uvemas** [comment]
The problem should be fixed after merging the pull request #52.
