### ISSUE TITLE
PyTables error

### ISSUE THREAD

**Issue by shacharm2** [uvemas/ViTables#54]
PyTables version 3.3.0
Trying to load any HDF5, or even openning ViTables results in an error.
It seems the pytables version changed names, such as openFile -> open_file 
ViTables does not recognize it 

File "/usr/share/vitables/vitables/h5db/dbDoc.py", line 115, in openH5File
    h5file = tables.openFile(self.filepath, self.mode)
AttributeError: 'module' object has no attribute 'openFile'

**Comment by uvemas** [comment]
Well, it seems that PyTables has migrated to its new API (see http://www.pytables.org/MIGRATING_TO_3.x.html, section Major API Changes) and the old API is not supported in PyTables 3.3.0 (accordingly to your bug report).  Unfortunately I have not migrated ViTables to use the new API. I will try to upgrade ViTables (help is really welcome) but until it happens I think your best option is to use an older version of PyTables One with support for both APIs should be fine.

Hope it helps.

**Comment by uvemas** [comment]
The problem should be fixed with commit a7dc694 so I close the bug.

**Comment by shacharm2** [comment]
@uvemas checking it out

**Comment by shacharm2** [comment]
@uvemas - tested and verified on Ubuntu 16.04 + python3 
thumbs up!

also tested not to work with python2 - does not work due str() that receives a utf-8 encoding
