### ISSUE TITLE
move to (vendored or not) QtPy

### ISSUE THREAD

**Issue by stonebig** [uvemas/ViTables#62]
a move of Pytables off from a direct Qt interface to an indirect "QtPy" would make it:
- usable for PyQt4/PyQt5/PySide2.
- more resistant to another Qt version change.

**Comment by cgohlke** [comment]
This might be as easy as replacing (case sensitive) `PyQt5 -> qtpy` and `QtCore.pyqt -> QtCore.` in all `.py` files. Seems to work for me with QtPy-1.2.1 and PyQt4-4.11.4 on Python 3.6, Windows.

**Comment by stonebig** [comment]
what about "@QtCore.pyqtSlot" ? should it be replaced also per "@pyqtSlot" ?

**Comment by stonebig** [comment]
I'll suppose yes

**Comment by stonebig** [comment]
issue, I may have done something wrong.

**Comment by stonebig** [comment]
as I wrote in the pull request, cgohlke patch is working great.
