### ISSUE TITLE
pytables now uses open_file instead of openFile

### ISSUE THREAD

**Issue by teslatech** [uvemas/ViTables#69]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/vitables/h5db/dbDoc.py", line 115, in openH5File
    h5file = tables.openFile(self.filepath, self.mode)
AttributeError: 'module' object has no attribute 'openFile'

pytables uses tables.open_file()

**Comment by uvemas** [comment]
Please, use a recent version  of ViTables. A few days ago 3.0.0 was released. I sent the announce to Python announce list but it is a moderated list...

**Comment by teslatech** [comment]
Sorry.  Just saw the package got flagged as out-of-date in my OS
repository.  Was rushing around too much at work yesterday.

BC

**Comment by uvemas** [comment]
No problem :-) Please, if you like the new version, consider give me a hand with #68. It would be great to have some more quotes there.
