### ISSUE TITLE
Blank fields in ViTables

### ISSUE THREAD

**Issue by laborleben** [uvemas/ViTables#83]
As of commit https://github.com/uvemas/ViTables/commit/d45f00811f21b9ea30b6e33931b2ecd9b4aa213f the fields are blank.

The issue is in line https://github.com/uvemas/ViTables/blame/d45f00811f21b9ea30b6e33931b2ecd9b4aa213f/vitables/vttables/leaf_model.py#L126, which should not be indented.

**Comment by uvemas** [comment]
Just merged. Thanks a lot!
