### ISSUE TITLE
DataFrame lost columns

### ISSUE THREAD

**Issue by mikeun** [uvemas/ViTables#88]
I created hdf5 by pandas DataFrame.
I opened it by vitables and can't find one column (last [-1]) and one column name (first [0]).
Column's names are shifted forward with missed first name and last column is hidden.
Table properties are shown all columns and names.
I use: 
- ViTables 3.0.0; 
- Python 3.6.2 |Anaconda custom (64-bit); 
- Ubuntu 16.04

**Comment by uvemas** [comment]
Thanks for your report. I think the problem here is that the DataFrame implementation (in the df_model.py) is not finished. I'll try to fix the problem but it can take some time to me as I'm not the author of the code.

**Comment by ankostis** [comment]
@mikeun would it be possible to craft a code creating the dataframe?

**Comment by uvemas** [comment]
I can reproduce the problem with this simple code:

`store = pd.HDFStore('my_store.hdf')`
`np.random.seed(1324)`
`index = pd.date_range('1/1/2017', periods=5)`
`df = pd.DataFrame(np.random.randn(5, 3), index=index, columns=['A', 'B', 'C'])`
`store.append('dataframe', df)`
`store.close()`
